# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(500, 151)
        Form.setMinimumSize(QtCore.QSize(500, 151))
        Form.setMaximumSize(QtCore.QSize(500, 151))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/favicon/favicon-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.databasePath_horizontalLayout = QtWidgets.QHBoxLayout()
        self.databasePath_horizontalLayout.setObjectName("databasePath_horizontalLayout")
        self.databasePath_label = QtWidgets.QLabel(Form)
        self.databasePath_label.setMinimumSize(QtCore.QSize(143, 0))
        self.databasePath_label.setObjectName("databasePath_label")
        self.databasePath_horizontalLayout.addWidget(self.databasePath_label)
        self.databasePath_lineEdit = QtWidgets.QLineEdit(Form)
        self.databasePath_lineEdit.setObjectName("databasePath_lineEdit")
        self.databasePath_horizontalLayout.addWidget(self.databasePath_lineEdit)
        self.databasePath_toolButton = QtWidgets.QToolButton(Form)
        self.databasePath_toolButton.setObjectName("databasePath_toolButton")
        self.databasePath_horizontalLayout.addWidget(self.databasePath_toolButton)
        self.verticalLayout.addLayout(self.databasePath_horizontalLayout)
        self.masterPassword_horizontalLayout = QtWidgets.QHBoxLayout()
        self.masterPassword_horizontalLayout.setObjectName("masterPassword_horizontalLayout")
        self.masterPassword_checkBox = QtWidgets.QCheckBox(Form)
        self.masterPassword_checkBox.setText("")
        self.masterPassword_checkBox.setObjectName("masterPassword_checkBox")
        self.masterPassword_horizontalLayout.addWidget(self.masterPassword_checkBox)
        self.masterPassword_label = QtWidgets.QLabel(Form)
        self.masterPassword_label.setObjectName("masterPassword_label")
        self.masterPassword_horizontalLayout.addWidget(self.masterPassword_label)
        self.masterPassword_lineEdit = QtWidgets.QLineEdit(Form)
        self.masterPassword_lineEdit.setObjectName("masterPassword_lineEdit")
        self.masterPassword_horizontalLayout.addWidget(self.masterPassword_lineEdit)
        self.masterPassword_toolButton = QtWidgets.QToolButton(Form)
        self.masterPassword_toolButton.setObjectName("masterPassword_toolButton")
        self.masterPassword_horizontalLayout.addWidget(self.masterPassword_toolButton)
        self.verticalLayout.addLayout(self.masterPassword_horizontalLayout)
        self.OTP_horizontalLayout = QtWidgets.QHBoxLayout()
        self.OTP_horizontalLayout.setObjectName("OTP_horizontalLayout")
        self.OTP_checkBox = QtWidgets.QCheckBox(Form)
        self.OTP_checkBox.setText("")
        self.OTP_checkBox.setObjectName("OTP_checkBox")
        self.OTP_horizontalLayout.addWidget(self.OTP_checkBox)
        self.OTP_label = QtWidgets.QLabel(Form)
        self.OTP_label.setMinimumSize(QtCore.QSize(120, 0))
        self.OTP_label.setObjectName("OTP_label")
        self.OTP_horizontalLayout.addWidget(self.OTP_label)
        self.OTP_lineEdit = QtWidgets.QLineEdit(Form)
        self.OTP_lineEdit.setObjectName("OTP_lineEdit")
        self.OTP_horizontalLayout.addWidget(self.OTP_lineEdit)
        self.OTP_toolButton = QtWidgets.QToolButton(Form)
        self.OTP_toolButton.setObjectName("OTP_toolButton")
        self.OTP_horizontalLayout.addWidget(self.OTP_toolButton)
        self.verticalLayout.addLayout(self.OTP_horizontalLayout)
        self.pushButton_horizontalLayout = QtWidgets.QHBoxLayout()
        self.pushButton_horizontalLayout.setObjectName("pushButton_horizontalLayout")
        self.OK_pushButton = QtWidgets.QPushButton(Form)
        self.OK_pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.pushButton_horizontalLayout.addWidget(self.OK_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(Form)
        self.cancel_pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.pushButton_horizontalLayout.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.pushButton_horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Open Database"))
        self.databasePath_label.setText(_translate("Form", "Database path"))
        self.databasePath_toolButton.setText(_translate("Form", "..."))
        self.masterPassword_label.setText(_translate("Form", "Master password"))
        self.masterPassword_toolButton.setText(_translate("Form", "..."))
        self.OTP_label.setText(_translate("Form", "OTP"))
        self.OTP_toolButton.setText(_translate("Form", "..."))
        self.OK_pushButton.setText(_translate("Form", "OK"))
        self.cancel_pushButton.setText(_translate("Form", "Cancel"))
